/**
 * Pure synthesis helpers for the backfill planner.
 *
 * Used in two contexts:
 *   - synthesize_orphans mode (S8): fabricate the paired cash leg for an
 *     orphan stock leg so lots wire up correctly.
 *   - drift variant A (S4 "separate_fee_row"): fabricate a fee row on the
 *     cash sleeve when stock-leg amount and cash-leg amount disagree.
 *
 * No DB writes. Returns plain SynthesizedRow objects the apply path will
 * INSERT with source='backfill_synth'.
 */

import type {
  SnapshotHolding,
  SnapshotTx,
  SynthesizedRow,
} from "./types";

/**
 * Build the paired cash leg for an orphan Buy or Sell stock leg.
 *
 * Convention from CLAUDE.md "Portfolio operations are two-row internal
 * swaps; stock leg amount POSITIVE, cash leg amount NEGATIVE; sum = 0":
 *   - Buy  → stock qty>0, stock amount>0; cash qty<0, cash amount<0
 *   - Sell → stock qty<0, stock amount<0; cash qty>0, cash amount>0
 *
 * The orphan stock row likely arrived with the legacy "amount = cash-out"
 * convention (qty=+10, amount=-2000 on a buy). The Phase 2 sign flip
 * happens in the replacement payload, not here — this helper sees the
 * already-normalized stock-leg amount.
 */
export function synthesizeCashLeg(
  stockTx: SnapshotTx,
  cashSleeve: SnapshotHolding,
  /** Normalized stock-leg amount under Phase 2 convention. POSITIVE on buy, NEGATIVE on sell. */
  normalizedStockAmount: number,
  /** Shared trade_link_id for the pair. Generated by the planner. */
  tradeLinkId: string,
): SynthesizedRow {
  const cashAmount = -normalizedStockAmount; // sum must be 0
  const isBuy = (stockTx.quantity ?? 0) > 0;
  return {
    date: stockTx.date,
    accountId: stockTx.accountId!,
    categoryId: stockTx.categoryId,
    portfolioHoldingId: cashSleeve.id,
    currency: cashSleeve.currency,
    amount: cashAmount,
    quantity: cashAmount, // cash-sleeve qty mirrors amount in the sleeve's own currency
    kind: isBuy ? "buy_cash_leg" : "sell_cash_leg",
    tradeLinkId,
    linkId: null,
    synthReason: isBuy
      ? `No cash debit found for buy of ${stockTx.quantity} units on ${stockTx.date}; synthesized to wire up lot tracking. Cash-sleeve balance will decrease by ${Math.abs(cashAmount).toFixed(2)} ${cashSleeve.currency}.`
      : `No cash credit found for sell of ${Math.abs(stockTx.quantity ?? 0)} units on ${stockTx.date}; synthesized to wire up lot tracking. Cash-sleeve balance will increase by ${Math.abs(cashAmount).toFixed(2)} ${cashSleeve.currency}.`,
  };
}

/**
 * Build a "Brokerage fee" row on the cash sleeve to absorb the drift
 * between stock-leg amount and cash-leg amount (S4 variant A).
 *
 * driftAmount = |stockAmount| - |cashAmount|. If positive, the cash side
 * paid MORE than the stock book value (i.e., fee is on the cash side).
 * The fee row is always a debit on the cash sleeve (negative qty + amount)
 * tagged kind='portfolio_expense' so it shows up in spend reports.
 */
export function synthesizeFeeRow(
  stockTx: SnapshotTx,
  cashSleeve: SnapshotHolding,
  driftAmount: number,
): SynthesizedRow {
  const feeMagnitude = Math.abs(driftAmount);
  return {
    date: stockTx.date,
    accountId: stockTx.accountId!,
    categoryId: stockTx.categoryId, // user's "Brokerage fee" category if mapped; else stays as the trade's category
    portfolioHoldingId: cashSleeve.id,
    currency: cashSleeve.currency,
    amount: -feeMagnitude,
    quantity: -feeMagnitude,
    kind: "portfolio_expense",
    tradeLinkId: null,
    linkId: null,
    synthReason: `Drift of ${feeMagnitude.toFixed(2)} ${cashSleeve.currency} between stock and cash leg on ${stockTx.date}; booked as a separate brokerage fee to preserve audit trail.`,
  };
}
